### ISSUE TITLE
ValueError: Input 0 is incompatible with layer efficientnetb0: expected shape=(None, 224, 224, 3), found shape=(32, 224, 3)

### ISSUE THREAD

**Issue by syu-tan** [Kazuhito00/FingerFrameLens#1]
cant work `main.py`.
the environment is  below;
- Mac OSX BigSur
- python 3.7.0
- cv2 4.5.1
- tensorflow 2.4.1

```
2021-04-28 08:20:37.495260: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
Traceback (most recent call last):
  File "main.py", line 254, in <module>
    main()
  File "main.py", line 187, in main
    effnet_model.predict(tensor)
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1629, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1478 predict_function  *
        return step_function(self, iterator)
    /Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1468 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1461 run_step  **
        outputs = model.predict_step(data)
    /Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1434 predict_step
        return self(x, training=False)
    /Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /Users/foge/anaconda3/envs/ai/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py:274 assert_input_compatibility
        ', found shape=' + display_shape(x.shape))

    ValueError: Input 0 is incompatible with layer efficientnetb0: expected shape=(None, 224, 224, 3), found shape=(32, 224, 3)
```

**Comment by syu-tan** [comment]
p.s.
I changed the environment to `tensorflow version == 2.3.0` and it worked.
Probably because you ignored ```WARNING:tensorflow:Model was constructed with shape (None, 224, 224, 3) for input Tensor("input_1:0", shape=(None, 224, 224, 3), dtype=float32), but it was called on an input with incompatible shape (32, 224, 3).```

I'm sorry I'm not very familiar with it and couldn't immediately propose a good improvement.
Since it is not compatible with the new environment, I thought it would be better to clarify it by introducing requirement.txt etc.

Thank you for your wonderful achievements!

**Comment by Kazuhito00** [comment]
Thank you for reporting the error.
I fixed it and confirmed the operation with TensorFlow 2.4.1.
However, I only have a Windows PC, so I haven't been able to confirm it on a Mac.

**Comment by Kazuhito00** [comment]
@syu-tan
Thank you for reporting the error.
I fixed it and confirmed the operation with TensorFlow 2.4.1.
However, I only have a Windows PC, so I haven't been able to confirm it on a Mac.

**Comment by syu-tan** [comment]
@Kazuhito00 
Thank you for your nice job.
i tried to check your update on Mac(OSX : BigSur)
its very fine work. 
Hope your app spreads!

**Comment by Kazuhito00** [comment]
Thank you for confirmation.
